### ISSUE TITLE
Calc every 1sec? Too harsh!

### ISSUE THREAD

**Issue by minhoryang** [taeguk/taeguk.github.io#1]
Code: https://github.com/taeguk/taeguk.github.io/blob/2e2b9c49bfa584466fbd90d88acc9fd9379576d6/index.html##L275-L284

Suggestion: Separate this to getting_current_time and ticking_one_second.

Snippet:
```javascript
getting_current_time();
setInterval(() => {
    if (sec != 0)
        ticking_one_second();
    else
        getting_current_time();
});
```

**Comment by taeguk** [comment]
ㅋㅋㅋㅋㅋㅋㅋㅋ 감사합니다. 제안 주신대로 수정할게요

**Comment by taeguk** [comment]
코드까지 보셨다니 ㅋㅋㅋ 막 짰는데 부끄럽군요 ㅎㅎㅎ
